clean up utility scripts and make collector run as 'aoc' user with 'upstart' (#186)
* enhance ctl script

* fix the breaking change on data model upgrades

* make the collector run as 'aoc' user with 'upstart'

diff --git a/tools/ctl/linux/aws-otel-collector-ctl b/tools/ctl/linux/aws-otel-collector-ctl
--- a/tools/ctl/linux/aws-otel-collector-ctl
+++ b/tools/ctl/linux/aws-otel-collector-ctl
@@ -1,39 +1,34 @@
-  #!/bin/sh
+#!/bin/sh
 
- # Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
- #
- # Licensed under the Apache License, Version 2.0 (the "License").
- # You may not use this file except in compliance with the License.
- # A copy of the License is located at
- #
- #     http://www.apache.org/licenses/LICENSE-2.0
- #
- # or in the "license" file accompanying this file. This file is distributed
- # on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
- # express or implied. See the License for the specific language governing
- # permissions and limitations under the License.
+# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License").
+# You may not use this file except in compliance with the License.
+# A copy of the License is located at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# or in the "license" file accompanying this file. This file is distributed
+# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
+# express or implied. See the License for the specific language governing
+# permissions and limitations under the License.
 
-  set -e
-  set -u
+set -e
+set -u
 
-  readonly AGENTDIR="/opt/aws/aws-otel-collector"
-  readonly CMDDIR="${AGENTDIR}/bin"
-  readonly CONFDIR="${AGENTDIR}/etc"
-  readonly DFT_CONFDIR="${AGENTDIR}/var"
-  readonly LOGDIR="${AGENTDIR}/logs"
-  readonly RESTART_FILE="${CONFDIR}/restart"
-  readonly VERSION_FILE="${CMDDIR}/VERSION"
-  username="aoc"
+readonly AGENTDIR="/opt/aws/aws-otel-collector"
+readonly CMDDIR="${AGENTDIR}/bin"
+readonly CONFDIR="${AGENTDIR}/etc"
+readonly DFT_CONFDIR="${AGENTDIR}/var"
+readonly LOGDIR="${AGENTDIR}/logs"
+readonly RESTART_FILE="${CONFDIR}/restart"
+readonly VERSION_FILE="${CMDDIR}/VERSION"
 
-  # The systemd and upstart scripts assume exactly this .toml file name
-  readonly TOML="${CONFDIR}/config.yaml"
-  readonly JSON_DIR="${CONFDIR}/aws-otel-collector.d"
+SYSTEMD='false'
 
-  SYSTEMD='false'
+UsageString="
 
-  UsageString="
-
-  usage: amazon-opentelemetry-collector-ctl -a stop|start|status| [-c file:<file-path>]
+  usage: aws-otel-collector-ctl -a stop|start|status| [-c file:<file-path>]
 
   e.g.
   1. start collector on onPermise host with a custom .yaml config file:
@@ -53,11 +48,11 @@
 
   "
 
-  aoc_start() {
+aoc_start() {
     config="${1:-}"
 
     if [ ! -z $config ] && [ -f $config ]; then
-          cp $config $CONFDIR/config.yaml
+        cp $config $CONFDIR/config.yaml
     fi
 
     if [ ! -f $CONFDIR/config.yaml ]; then
@@ -65,48 +60,48 @@
     fi
 
     if [ "${SYSTEMD}" = 'true' ]; then
-      systemctl daemon-reload
-      systemctl enable aws-otel-collector.service
-      service aws-otel-collector restart
+        systemctl daemon-reload
+        systemctl enable aws-otel-collector.service
+        service aws-otel-collector restart
     else
-      start aws-otel-collector
-      sleep 1
+        start aws-otel-collector
+        sleep 1
     fi
-  }
+}
 
-  aoc_stop() {
+aoc_stop() {
     if [ "$(aoc_runstatus)" = 'stopped' ]; then
-      return 0
+        return 0
     fi
 
     if [ "${SYSTEMD}" = 'true' ]; then
-      service aws-otel-collector stop
+        service aws-otel-collector stop
     else
-      stop aws-otel-collector || true
+        stop aws-otel-collector || true
     fi
-  }
+}
 
-  aoc_preun() {
+aoc_preun() {
     aoc_stop
     if [ "${SYSTEMD}" = 'true' ]; then
-      systemctl disable aws-otel-collector.service
-      systemctl daemon-reload
-      systemctl reset-failed
+        systemctl disable aws-otel-collector.service
+        systemctl daemon-reload
+        systemctl reset-failed
     fi
-  }
+}
 
-  aoc_status() {
+aoc_status() {
     pid=''
     if [ "${SYSTEMD}" = 'true' ]; then
-      pid="$(systemctl show -p MainPID aws-otel-collector.service | sed s/MainPID=//)"
+        pid="$(systemctl show -p MainPID aws-otel-collector.service | sed s/MainPID=//)"
     else
-      pid="$(initctl status aws-otel-collector | sed -n s/^.*process\ //p)"
+        pid="$(initctl status aws-otel-collector | sed -n s/^.*process\ //p)"
     fi
 
     starttime_fmt=''
     if [ ${pid} ] && [ ${pid} -ne 0 ]; then
-      starttime="$(TZ=UTC ps -o lstart= "${pid}")"
-      starttime_fmt="$(TZ=UTC date -Isec -d "${starttime}")"
+        starttime="$(TZ=UTC ps -o lstart= "${pid}")"
+        starttime_fmt="$(TZ=UTC date -Isec -d "${starttime}")"
     fi
 
     version="$(cat ${VERSION_FILE})"
@@ -116,89 +111,94 @@
     echo "  \"starttime\": \"${starttime_fmt}\","
     echo "  \"version\": \"${version}\""
     echo "}"
-  }
+}
 
-  aoc_runstatus() {
+aoc_runstatus() {
     running=false
     if [ "${SYSTEMD}" = 'true' ]; then
-      set +e
-      if systemctl is-active aws-otel-collector.service 1>/dev/null; then
-        running='true'
-      fi
-      set -e
+        set +e
+        if systemctl is-active aws-otel-collector.service 1>/dev/null; then
+            running='true'
+        fi
+        set -e
     else
-      if [ "$(initctl status aws-otel-collector | grep -c running)" = 1 ]; then
-        running='true'
-      fi
+        if [ "$(initctl status aws-otel-collector | grep -c running)" = 1 ]; then
+            running='true'
+        fi
     fi
 
     if [ "${running}" = 'true' ]; then
-      echo "running"
+        echo "running"
     else
-      echo "stopped"
+        echo "stopped"
     fi
-  }
+}
 
-    main() {
-      action=''
-      restart='false'
-      mode='ec2'
-      config_location=''
+main() {
+    action=''
+    restart='false'
+    mode='ec2'
+    config_location=''
 
-      # detect which init system is in use
-      if [ "$(/sbin/init --version 2>/dev/null | grep -c upstart)" = 1 ]; then
+    # detect which init system is in use
+    if [ "$(/sbin/init --version 2>/dev/null | grep -c upstart)" = 1 ]; then
         SYSTEMD='false'
-      elif [ "$(systemctl | grep -c '\-\.mount')" = 1 ]; then
+    elif [ "$(systemctl | grep -c '\-\.mount')" = 1 ]; then
         SYSTEMD='true'
-      elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
+    elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
         echo "sysv-init is not supported" >&2
         exit 1
-      else
+    else
         echo "unknown init system" >&2
         exit 1
-      fi
+    fi
 
-      OPTIND=1
-      while getopts ":hsa:r:c:m:" opt; do
+    OPTIND=1
+    while getopts ":hsa:r:c:m:" opt; do
         case "${opt}" in
-          h) echo "${UsageString}"
-        exit 0
-        ;;
+        h)
+            echo "${UsageString}"
+            exit 0
+            ;;
         s) restart='true' ;;
         a) action="${OPTARG}" ;;
         c) config_location="${OPTARG}" ;;
         m) mode="${OPTARG}" ;;
-        \?) echo "Invalid option: -${OPTARG} ${UsageString}" >&2
-        ;;
-        :)  echo "Option -${OPTARG} requires an argument ${UsageString}" >&2
+        \?)
+            echo "Invalid option: -${OPTARG} ${UsageString}" >&2
+            ;;
+        :)
+            echo "Option -${OPTARG} requires an argument ${UsageString}" >&2
+            exit 1
+            ;;
+        esac
+    done
+    shift "$((${OPTIND} - 1))"
+
+    case "${mode}" in
+    ec2) ;;
+
+    onPremise) ;;
+
+    auto) ;;
+
+    *)
+        echo "Invalid mode: ${mode} ${UsageString}" >&2
         exit 1
         ;;
-      esac
-      done
-shift "$(( ${OPTIND} - 1 ))"
+    esac
 
-case "${mode}" in
-  ec2)
-  ;;
-  onPremise)
-  ;;
-  auto)
-  ;;
-  *)  echo "Invalid mode: ${mode} ${UsageString}" >&2
-  exit 1
-  ;;
-esac
-
-case "${action}" in
-  stop) aoc_stop ;;
-  start) aoc_start "${config_location}" ;;
-  status) aoc_status ;;
-  # helper for rpm+deb uninstallation hooks, not expected to be called manually
-  preun) aoc_preun ;;
-  *) echo "Invalid action: ${action} ${UsageString}" >&2
-  exit 1
-  ;;
-esac
+    case "${action}" in
+    stop) aoc_stop ;;
+    start) aoc_start "${config_location}" ;;
+    status) aoc_status ;;
+    # helper for rpm+deb uninstallation hooks, not expected to be called manually
+    preun) aoc_preun ;;
+    *)
+        echo "Invalid action: ${action} ${UsageString}" >&2
+        exit 1
+        ;;
+    esac
 }
 
 main "$@"
