update error output

diff --git a/.github/workflows/pr-body-validate.yml b/.github/workflows/pr-body-validate.yml
--- a/.github/workflows/pr-body-validate.yml
+++ b/.github/workflows/pr-body-validate.yml
@@ -29,6 +29,6 @@ jobs:
               if echo "${{ github.event.pull_request.body }}" | grep -q "${{ env.LICENSE_TEXT }}" ; then 
                 echo "License text found in PR body"
               else
-                echo "License text not found in PR Body, refer to PR template" && exit 1
+                echo "License text not found in PR Body. PR Body requires \"${{ env.LICENSE_TEXT }}\"" && exit 1
               fi
 
