Update quotations

diff --git a/.github/workflows/pr-body-validate.yml b/.github/workflows/pr-body-validate.yml
--- a/.github/workflows/pr-body-validate.yml
+++ b/.github/workflows/pr-body-validate.yml
@@ -27,9 +27,9 @@ jobs:
         - name: Validade license content
           if: ${{ github.actor != 'dependabot[bot]' }} 
           run: | 
-              if echo "${{ github.event.pull_request.body }}" | grep -q "${{ env.LICENSE_TEXT }}" ; then 
+              if echo '${{ github.event.pull_request.body }}' | grep -q '${{ env.LICENSE_TEXT }}' ; then 
                 echo "License text found in PR body"
               else
-                echo "License text not found in PR Body. PR Body requires \"${{ env.LICENSE_TEXT }}\"" && exit 1
+                echo 'License text not found in PR Body. PR Body requires \"${{ env.LICENSE_TEXT }}\"' && exit 1
               fi
 
